version: '2'
volumes:
  settings:
services:
  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    ports:
      - 5011:5011
      - 35173:35173
    volumes:
      - 'settings:/data'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
