version: '2'
volumes:
  settings:
services:
  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    ports:
      - 5011:5011
      - 35174:35174
    volumes:
      - 'settings:/data'
    labels:
      io.balena.features.supervisor-api: '1'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
