FROM bh.cr/balenalabs/browser-%%BALENA_ARCH%%/2.7.0

RUN install_packages socat

COPY scripts /usr/src/
RUN chmod +x /usr/src/*.sh

COPY udev /etc/udev/rules.d/

CMD ["/usr/src/start-remote-debug.sh"]
